version: '3.8'
services:
  postgres:
    image: postgres:14.9
    container_name: "finology"
    restart: always
    ports:
      - "5458:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata_data:/var/lib/postgresql/data
volumes:
  pgdata_data:
